전남대 17조 FE 3주차 PR
kakao-tech-campus-2nd-step3/Team17_FE pull request #12
Opened 2024-09-20 13:14 UTC by yunn23

안녕하세요 멘토님! 전남대 17조 FE 팀입니다.
저희 팀은 홈트 관련 웹을 기획하여, 모바일 사이즈 웹으로 제작할 예정이며, css는 emotion styled를 사용할 계획입니다.
이번주에는 추석 연휴가 겹쳐 프로젝트 세팅을 마치고, 이제 막 개발을 시작하게 되어 진행이 조금 더딘 것 같습니다. 일정에 차질이 생기지 않도록 계획한 일정에서 벗어나지 않도록 노력하겠습니다. Step3 기간 동안 잘 부탁드립니다!

## To do
**서윤**
- 프로젝트 초기세팅
- 메인화면 날짜 컴포넌트 구현

**도현**
- 로그인 페이지 생성 (스텝2 코드를 기반으로 틀만 잡음)

## 이슈
- `Cannot read file '/Users/seoyun/Desktop/cnu_workspace/hometry-fe/node_modules/react-day-picker/tsconfig-base.json'.` 에러 발생 (react-day-picker가 예상하는 tsconfig-base.json 파일이 node_moudles 내에 없음)
  - 이를 해결하기 위해 패키지 삭제후 재설치 해보았지만 동일 오류 지속적으로 발생하고 있습니다.
  - 프로젝트 실행에는 문제 없는 치명적이지 않은 오류이고 해결 방법을 찾지 못해 부득이하게 pr에 포함하였습니다. 혹시 어떻게 해결하는 것이 좋을까요?
  
    <img width="916" alt="image" src="https://github.com/user-attachments/assets/90828da5-0aeb-4e97-aea0-b82a740eacb3">

 
- 초기에 브랜치의 base 설정을 잘못해서 pr 생성이 안 되는 문제가 발생했으나 upstream에서 브랜치를 삭제하고 재생성해 해결 완료하였습니다!

2024-09-20 14:02 UTC, taehwanno requested changes
안녕하세요, 살펴보고 피드백드려요 ㅎㅎ
Step 3도 잘 부탁드리겠습니다!

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +    "start": "react-scripts start",
`npm start` 실행시 lint warning이 검출되고 있는데 한번 개선해보면 좋겠습니다.

<img width="666" alt="image" src="https://github.com/user-attachments/assets/f0473bf1-0ba9-4f73-9c75-adb5d558c565">

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +{
> Cannot read file '/Users/seoyun/Desktop/cnu_workspace/hometry-fe/node_modules/react-day-picker/tsconfig-base.json'. 에러 발생 (react-day-picker가 예상하는 tsconfig-base.json 파일이 node_moudles 내에 없음)

PR 본문에 적어주신 에러는 저는 감지가 안되고 있는데, 무엇을 실행해야 에러가 발생하던가용? VSCode Problems에서도 검출되진 않네용 🤔

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +    "lint:fix": "eslint --fix './src/**/*.{ts,tsx,js,jsx}'",
lint 적용하신다면 git commit 할 때 자동으로 lint 검사 및 autofix 적용될 수 있게 [husky](https://typicode.github.io/husky/)와 [lint-staged](https://github.com/lint-staged/lint-staged) 적용하는게 좋을 거 같은데 한번 검토해봐주시겠어요?

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +    "prettier": "prettier --write --config ./.prettierrc './src/**/*.{ts,tsx}'"
여러 인원이 같이 개발하는 걸로 알고 있는데요, 여러 브랜치가 생기면 포맷팅, 린트, 테스트, 빌드가 제대로 동작하는게 중요해서 CI 도구를 적용해보면 어떨까요? [Node.js 빌드 및 테스트](https://docs.github.com/ko/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs) 문서를 참고하셔서 GitHub Actions를 설정해보면 될 거 같은데 한번 검토 후 의견 부탁드릴게요.

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +  },
`.eslintrc`로 파일 분리해서 eslint 관련 설정 관리하기 때문에 package.json에서 eslintConfig는 제거해도 될 거 같아용

```suggestion
  }
```

2024-09-20 14:02 UTC, taehwanno commented on package.json
> +  "name": "hometry-fe",
폴더 구조는 팀원끼리 어떤 기준으로 합의해서 코드 구현하게 될 지 README.md에 한번 정리해봐주실 수 있을까요? README에 적어두면 팀에 소속된 팀원 간에 시야도 정렬하는 효과가 있을거라 한번 부탁드려봅니다.

2024-09-23 06:48 UTC, yunn23 commented on package.json
> +    "start": "react-scripts start",
![image](https://github.com/user-attachments/assets/c1607e60-ac64-4f6f-bb78-3132b58b6aab)

제 로컬에서는 npm start시 경고가 뜨지 않는데 로컬마다 다를수도 있나요?

2024-09-23 06:56 UTC, yunn23 commented on package.json
> +{
아무것도 실행하지 않아도 에러가 떠있습니다! react-day-picker을 설치하면서 node_modules 관련 에러인 것 같은데 다음 제출물때 npm install 관련해서 개선할 수 있는지 확인해보겠습니다.

2024-09-23 06:56 UTC, yunn23 commented on package.json
> +    "prettier": "prettier --write --config ./.prettierrc './src/**/*.{ts,tsx}'"
관련 문서 읽어본 후 팀원과 논의해보도록 하겠습니다.

2024-09-23 06:58 UTC, yunn23 commented on package.json
> +  "name": "hometry-fe",
네 알겠습니다!

2024-09-23 12:19 UTC, taehwanno approved these changes
시기상 먼저 병합해두겠습니다 ㅎㅎ 피드백 드린 부분은 점진적으로 챙겨보시죠

2024-09-23 12:19 UTC, merged